name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
    - main
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Giving permission
        run: chmod +x ./project/tests.sh

      - name: Running tests
        run: bash ./project/tests.sh
     
